server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #测试服务器
    url: jdbc:mysql://rm-wz9d21p5za0w2ja2xo.mysql.rds.aliyuncs.com:3306/ump?autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8
    username: umpuser
    password: W6wRSvUD6TcYY17W
    http:
      multipart-maxFileSize: 10MB
      multipart-maxRequestSize: 10MB
  jmx:
    enabled: false
  application:
    name: eparkingUMPdata
  security:
    user:
      name: admin
      password: 123456
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    mode: LEGACYHTML5
    static-path-pattern: /static/**
    charset: UTF-8 #编码格式
    template-loader-path: classpath:/templates/
  messages:
      basename: messages
  session:
    store-type: redis
    timeout: 3600
    redis:
      flush-mode: on_save
      namespace:
        spring: session
  redis:
      host: 47.113.101.127
      port: 6379
      password: root
      timeout: 5000
      jedis:
        pool:
          max-wait: 30000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-active: 200 #最大连接数
          max-idle: 20 #最大空闲连接数
          min-idle: 0  #最小空闲连接数
eureka:
  instance:
      hostname: yun2.eparking.top
      instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
      lease-renewal-interval-in-seconds: 10    #配置续约更新时间
      lease-expiration-duration-in-seconds: 10   #配置续约到期时间
      #优先使用IP地址注册服务
      prefer-ip-address: true
  client:
    healthcheck:
      enabled: true #开启健康检查
    serviceUrl:
      defaultZone: https://${spring.security.user.name}:${spring.security.user.password}@yun2.eparking.top:8643/eureka/eureka/,https://${spring.security.user.name}:${spring.security.user.password}@yun2.eparking.top:8743/eureka/eureka/
  feign:
    httpclient:
      enabled: true
    hystrix:
      enabled: true
  hystrix:
      shareSecurityContext: true
      command:
        default:
          circuitBreaker:
            sleepWindowInMilliseconds: 100000
            forceClosed: true
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 600000
feign:
    hystrix:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql

logging:
  level:
    com:
      ump:
        dao: debug
websocket:
  url: ws://192.168.10.104:8087/websocket/
