package com.ump.entity;

public class TAlarmMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.park_name
     *
     * @mbg.generated
     */
    private String parkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.port_id
     *
     * @mbg.generated
     */
    private String portId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.port_name
     *
     * @mbg.generated
     */
    private String portName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.inoutType
     *
     * @mbg.generated
     */
    private Integer inouttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.computer_name
     *
     * @mbg.generated
     */
    private String computerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.online_status
     *
     * @mbg.generated
     */
    private Integer onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.carIn_flow
     *
     * @mbg.generated
     */
    private String carinFlow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.groud_sensor_camera
     *
     * @mbg.generated
     */
    private Integer groudSensorCamera;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.groud_sensor_banister
     *
     * @mbg.generated
     */
    private Integer groudSensorBanister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.camera_staus
     *
     * @mbg.generated
     */
    private Integer cameraStaus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.banister_status
     *
     * @mbg.generated
     */
    private Integer banisterStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.alarm_status
     *
     * @mbg.generated
     */
    private Integer alarmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.lane_status
     *
     * @mbg.generated
     */
    private Integer laneStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.alarm_level
     *
     * @mbg.generated
     */
    private Integer alarmLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.alarm_time
     *
     * @mbg.generated
     */
    private String alarmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.deal_status
     *
     * @mbg.generated
     */
    private Integer dealStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_alarm_message.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.id
     *
     * @return the value of t_alarm_message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.id
     *
     * @param id the value for t_alarm_message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.park_id
     *
     * @return the value of t_alarm_message.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.park_id
     *
     * @param parkId the value for t_alarm_message.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.park_name
     *
     * @return the value of t_alarm_message.park_name
     *
     * @mbg.generated
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.park_name
     *
     * @param parkName the value for t_alarm_message.park_name
     *
     * @mbg.generated
     */
    public void setParkName(String parkName) {
        this.parkName = parkName == null ? null : parkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.port_id
     *
     * @return the value of t_alarm_message.port_id
     *
     * @mbg.generated
     */
    public String getPortId() {
        return portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.port_id
     *
     * @param portId the value for t_alarm_message.port_id
     *
     * @mbg.generated
     */
    public void setPortId(String portId) {
        this.portId = portId == null ? null : portId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.port_name
     *
     * @return the value of t_alarm_message.port_name
     *
     * @mbg.generated
     */
    public String getPortName() {
        return portName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.port_name
     *
     * @param portName the value for t_alarm_message.port_name
     *
     * @mbg.generated
     */
    public void setPortName(String portName) {
        this.portName = portName == null ? null : portName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.inoutType
     *
     * @return the value of t_alarm_message.inoutType
     *
     * @mbg.generated
     */
    public Integer getInouttype() {
        return inouttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.inoutType
     *
     * @param inouttype the value for t_alarm_message.inoutType
     *
     * @mbg.generated
     */
    public void setInouttype(Integer inouttype) {
        this.inouttype = inouttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.computer_name
     *
     * @return the value of t_alarm_message.computer_name
     *
     * @mbg.generated
     */
    public String getComputerName() {
        return computerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.computer_name
     *
     * @param computerName the value for t_alarm_message.computer_name
     *
     * @mbg.generated
     */
    public void setComputerName(String computerName) {
        this.computerName = computerName == null ? null : computerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.online_status
     *
     * @return the value of t_alarm_message.online_status
     *
     * @mbg.generated
     */
    public Integer getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.online_status
     *
     * @param onlineStatus the value for t_alarm_message.online_status
     *
     * @mbg.generated
     */
    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.carIn_flow
     *
     * @return the value of t_alarm_message.carIn_flow
     *
     * @mbg.generated
     */
    public String getCarinFlow() {
        return carinFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.carIn_flow
     *
     * @param carinFlow the value for t_alarm_message.carIn_flow
     *
     * @mbg.generated
     */
    public void setCarinFlow(String carinFlow) {
        this.carinFlow = carinFlow == null ? null : carinFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.groud_sensor_camera
     *
     * @return the value of t_alarm_message.groud_sensor_camera
     *
     * @mbg.generated
     */
    public Integer getGroudSensorCamera() {
        return groudSensorCamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.groud_sensor_camera
     *
     * @param groudSensorCamera the value for t_alarm_message.groud_sensor_camera
     *
     * @mbg.generated
     */
    public void setGroudSensorCamera(Integer groudSensorCamera) {
        this.groudSensorCamera = groudSensorCamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.groud_sensor_banister
     *
     * @return the value of t_alarm_message.groud_sensor_banister
     *
     * @mbg.generated
     */
    public Integer getGroudSensorBanister() {
        return groudSensorBanister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.groud_sensor_banister
     *
     * @param groudSensorBanister the value for t_alarm_message.groud_sensor_banister
     *
     * @mbg.generated
     */
    public void setGroudSensorBanister(Integer groudSensorBanister) {
        this.groudSensorBanister = groudSensorBanister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.camera_staus
     *
     * @return the value of t_alarm_message.camera_staus
     *
     * @mbg.generated
     */
    public Integer getCameraStaus() {
        return cameraStaus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.camera_staus
     *
     * @param cameraStaus the value for t_alarm_message.camera_staus
     *
     * @mbg.generated
     */
    public void setCameraStaus(Integer cameraStaus) {
        this.cameraStaus = cameraStaus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.banister_status
     *
     * @return the value of t_alarm_message.banister_status
     *
     * @mbg.generated
     */
    public Integer getBanisterStatus() {
        return banisterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.banister_status
     *
     * @param banisterStatus the value for t_alarm_message.banister_status
     *
     * @mbg.generated
     */
    public void setBanisterStatus(Integer banisterStatus) {
        this.banisterStatus = banisterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.alarm_status
     *
     * @return the value of t_alarm_message.alarm_status
     *
     * @mbg.generated
     */
    public Integer getAlarmStatus() {
        return alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.alarm_status
     *
     * @param alarmStatus the value for t_alarm_message.alarm_status
     *
     * @mbg.generated
     */
    public void setAlarmStatus(Integer alarmStatus) {
        this.alarmStatus = alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.lane_status
     *
     * @return the value of t_alarm_message.lane_status
     *
     * @mbg.generated
     */
    public Integer getLaneStatus() {
        return laneStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.lane_status
     *
     * @param laneStatus the value for t_alarm_message.lane_status
     *
     * @mbg.generated
     */
    public void setLaneStatus(Integer laneStatus) {
        this.laneStatus = laneStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.alarm_level
     *
     * @return the value of t_alarm_message.alarm_level
     *
     * @mbg.generated
     */
    public Integer getAlarmLevel() {
        return alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.alarm_level
     *
     * @param alarmLevel the value for t_alarm_message.alarm_level
     *
     * @mbg.generated
     */
    public void setAlarmLevel(Integer alarmLevel) {
        this.alarmLevel = alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.alarm_time
     *
     * @return the value of t_alarm_message.alarm_time
     *
     * @mbg.generated
     */
    public String getAlarmTime() {
        return alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.alarm_time
     *
     * @param alarmTime the value for t_alarm_message.alarm_time
     *
     * @mbg.generated
     */
    public void setAlarmTime(String alarmTime) {
        this.alarmTime = alarmTime == null ? null : alarmTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.deal_status
     *
     * @return the value of t_alarm_message.deal_status
     *
     * @mbg.generated
     */
    public Integer getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.deal_status
     *
     * @param dealStatus the value for t_alarm_message.deal_status
     *
     * @mbg.generated
     */
    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.user_id
     *
     * @return the value of t_alarm_message.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.user_id
     *
     * @param userId the value for t_alarm_message.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.user_name
     *
     * @return the value of t_alarm_message.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.user_name
     *
     * @param userName the value for t_alarm_message.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_alarm_message.create_time
     *
     * @return the value of t_alarm_message.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_alarm_message.create_time
     *
     * @param createTime the value for t_alarm_message.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}