package com.ump.entity;

import java.util.ArrayList;
import java.util.List;

public class TAlarmMessageCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public TAlarmMessageCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNull() {
            addCriterion("park_id is null");
            return (Criteria) this;
        }

        public Criteria andParkIdIsNotNull() {
            addCriterion("park_id is not null");
            return (Criteria) this;
        }

        public Criteria andParkIdEqualTo(Integer value) {
            addCriterion("park_id =", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotEqualTo(Integer value) {
            addCriterion("park_id <>", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThan(Integer value) {
            addCriterion("park_id >", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("park_id >=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThan(Integer value) {
            addCriterion("park_id <", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdLessThanOrEqualTo(Integer value) {
            addCriterion("park_id <=", value, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdIn(List<Integer> values) {
            addCriterion("park_id in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotIn(List<Integer> values) {
            addCriterion("park_id not in", values, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdBetween(Integer value1, Integer value2) {
            addCriterion("park_id between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("park_id not between", value1, value2, "parkId");
            return (Criteria) this;
        }

        public Criteria andParkNameIsNull() {
            addCriterion("park_name is null");
            return (Criteria) this;
        }

        public Criteria andParkNameIsNotNull() {
            addCriterion("park_name is not null");
            return (Criteria) this;
        }

        public Criteria andParkNameEqualTo(String value) {
            addCriterion("park_name =", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameNotEqualTo(String value) {
            addCriterion("park_name <>", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameGreaterThan(String value) {
            addCriterion("park_name >", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameGreaterThanOrEqualTo(String value) {
            addCriterion("park_name >=", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameLessThan(String value) {
            addCriterion("park_name <", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameLessThanOrEqualTo(String value) {
            addCriterion("park_name <=", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameLike(String value) {
            addCriterion("park_name like", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameNotLike(String value) {
            addCriterion("park_name not like", value, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameIn(List<String> values) {
            addCriterion("park_name in", values, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameNotIn(List<String> values) {
            addCriterion("park_name not in", values, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameBetween(String value1, String value2) {
            addCriterion("park_name between", value1, value2, "parkName");
            return (Criteria) this;
        }

        public Criteria andParkNameNotBetween(String value1, String value2) {
            addCriterion("park_name not between", value1, value2, "parkName");
            return (Criteria) this;
        }

        public Criteria andPortIdIsNull() {
            addCriterion("port_id is null");
            return (Criteria) this;
        }

        public Criteria andPortIdIsNotNull() {
            addCriterion("port_id is not null");
            return (Criteria) this;
        }

        public Criteria andPortIdEqualTo(String value) {
            addCriterion("port_id =", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotEqualTo(String value) {
            addCriterion("port_id <>", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdGreaterThan(String value) {
            addCriterion("port_id >", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdGreaterThanOrEqualTo(String value) {
            addCriterion("port_id >=", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdLessThan(String value) {
            addCriterion("port_id <", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdLessThanOrEqualTo(String value) {
            addCriterion("port_id <=", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdLike(String value) {
            addCriterion("port_id like", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotLike(String value) {
            addCriterion("port_id not like", value, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdIn(List<String> values) {
            addCriterion("port_id in", values, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotIn(List<String> values) {
            addCriterion("port_id not in", values, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdBetween(String value1, String value2) {
            addCriterion("port_id between", value1, value2, "portId");
            return (Criteria) this;
        }

        public Criteria andPortIdNotBetween(String value1, String value2) {
            addCriterion("port_id not between", value1, value2, "portId");
            return (Criteria) this;
        }

        public Criteria andPortNameIsNull() {
            addCriterion("port_name is null");
            return (Criteria) this;
        }

        public Criteria andPortNameIsNotNull() {
            addCriterion("port_name is not null");
            return (Criteria) this;
        }

        public Criteria andPortNameEqualTo(String value) {
            addCriterion("port_name =", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameNotEqualTo(String value) {
            addCriterion("port_name <>", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameGreaterThan(String value) {
            addCriterion("port_name >", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameGreaterThanOrEqualTo(String value) {
            addCriterion("port_name >=", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameLessThan(String value) {
            addCriterion("port_name <", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameLessThanOrEqualTo(String value) {
            addCriterion("port_name <=", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameLike(String value) {
            addCriterion("port_name like", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameNotLike(String value) {
            addCriterion("port_name not like", value, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameIn(List<String> values) {
            addCriterion("port_name in", values, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameNotIn(List<String> values) {
            addCriterion("port_name not in", values, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameBetween(String value1, String value2) {
            addCriterion("port_name between", value1, value2, "portName");
            return (Criteria) this;
        }

        public Criteria andPortNameNotBetween(String value1, String value2) {
            addCriterion("port_name not between", value1, value2, "portName");
            return (Criteria) this;
        }

        public Criteria andInouttypeIsNull() {
            addCriterion("inoutType is null");
            return (Criteria) this;
        }

        public Criteria andInouttypeIsNotNull() {
            addCriterion("inoutType is not null");
            return (Criteria) this;
        }

        public Criteria andInouttypeEqualTo(Integer value) {
            addCriterion("inoutType =", value, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeNotEqualTo(Integer value) {
            addCriterion("inoutType <>", value, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeGreaterThan(Integer value) {
            addCriterion("inoutType >", value, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("inoutType >=", value, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeLessThan(Integer value) {
            addCriterion("inoutType <", value, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeLessThanOrEqualTo(Integer value) {
            addCriterion("inoutType <=", value, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeIn(List<Integer> values) {
            addCriterion("inoutType in", values, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeNotIn(List<Integer> values) {
            addCriterion("inoutType not in", values, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeBetween(Integer value1, Integer value2) {
            addCriterion("inoutType between", value1, value2, "inouttype");
            return (Criteria) this;
        }

        public Criteria andInouttypeNotBetween(Integer value1, Integer value2) {
            addCriterion("inoutType not between", value1, value2, "inouttype");
            return (Criteria) this;
        }

        public Criteria andComputerNameIsNull() {
            addCriterion("computer_name is null");
            return (Criteria) this;
        }

        public Criteria andComputerNameIsNotNull() {
            addCriterion("computer_name is not null");
            return (Criteria) this;
        }

        public Criteria andComputerNameEqualTo(String value) {
            addCriterion("computer_name =", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameNotEqualTo(String value) {
            addCriterion("computer_name <>", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameGreaterThan(String value) {
            addCriterion("computer_name >", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameGreaterThanOrEqualTo(String value) {
            addCriterion("computer_name >=", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameLessThan(String value) {
            addCriterion("computer_name <", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameLessThanOrEqualTo(String value) {
            addCriterion("computer_name <=", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameLike(String value) {
            addCriterion("computer_name like", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameNotLike(String value) {
            addCriterion("computer_name not like", value, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameIn(List<String> values) {
            addCriterion("computer_name in", values, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameNotIn(List<String> values) {
            addCriterion("computer_name not in", values, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameBetween(String value1, String value2) {
            addCriterion("computer_name between", value1, value2, "computerName");
            return (Criteria) this;
        }

        public Criteria andComputerNameNotBetween(String value1, String value2) {
            addCriterion("computer_name not between", value1, value2, "computerName");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIsNull() {
            addCriterion("online_status is null");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIsNotNull() {
            addCriterion("online_status is not null");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusEqualTo(Integer value) {
            addCriterion("online_status =", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotEqualTo(Integer value) {
            addCriterion("online_status <>", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusGreaterThan(Integer value) {
            addCriterion("online_status >", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("online_status >=", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusLessThan(Integer value) {
            addCriterion("online_status <", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusLessThanOrEqualTo(Integer value) {
            addCriterion("online_status <=", value, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusIn(List<Integer> values) {
            addCriterion("online_status in", values, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotIn(List<Integer> values) {
            addCriterion("online_status not in", values, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusBetween(Integer value1, Integer value2) {
            addCriterion("online_status between", value1, value2, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andOnlineStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("online_status not between", value1, value2, "onlineStatus");
            return (Criteria) this;
        }

        public Criteria andCarinFlowIsNull() {
            addCriterion("carIn_flow is null");
            return (Criteria) this;
        }

        public Criteria andCarinFlowIsNotNull() {
            addCriterion("carIn_flow is not null");
            return (Criteria) this;
        }

        public Criteria andCarinFlowEqualTo(String value) {
            addCriterion("carIn_flow =", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowNotEqualTo(String value) {
            addCriterion("carIn_flow <>", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowGreaterThan(String value) {
            addCriterion("carIn_flow >", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowGreaterThanOrEqualTo(String value) {
            addCriterion("carIn_flow >=", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowLessThan(String value) {
            addCriterion("carIn_flow <", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowLessThanOrEqualTo(String value) {
            addCriterion("carIn_flow <=", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowLike(String value) {
            addCriterion("carIn_flow like", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowNotLike(String value) {
            addCriterion("carIn_flow not like", value, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowIn(List<String> values) {
            addCriterion("carIn_flow in", values, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowNotIn(List<String> values) {
            addCriterion("carIn_flow not in", values, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowBetween(String value1, String value2) {
            addCriterion("carIn_flow between", value1, value2, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andCarinFlowNotBetween(String value1, String value2) {
            addCriterion("carIn_flow not between", value1, value2, "carinFlow");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraIsNull() {
            addCriterion("groud_sensor_camera is null");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraIsNotNull() {
            addCriterion("groud_sensor_camera is not null");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraEqualTo(Integer value) {
            addCriterion("groud_sensor_camera =", value, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraNotEqualTo(Integer value) {
            addCriterion("groud_sensor_camera <>", value, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraGreaterThan(Integer value) {
            addCriterion("groud_sensor_camera >", value, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraGreaterThanOrEqualTo(Integer value) {
            addCriterion("groud_sensor_camera >=", value, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraLessThan(Integer value) {
            addCriterion("groud_sensor_camera <", value, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraLessThanOrEqualTo(Integer value) {
            addCriterion("groud_sensor_camera <=", value, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraIn(List<Integer> values) {
            addCriterion("groud_sensor_camera in", values, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraNotIn(List<Integer> values) {
            addCriterion("groud_sensor_camera not in", values, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraBetween(Integer value1, Integer value2) {
            addCriterion("groud_sensor_camera between", value1, value2, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorCameraNotBetween(Integer value1, Integer value2) {
            addCriterion("groud_sensor_camera not between", value1, value2, "groudSensorCamera");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterIsNull() {
            addCriterion("groud_sensor_banister is null");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterIsNotNull() {
            addCriterion("groud_sensor_banister is not null");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterEqualTo(Integer value) {
            addCriterion("groud_sensor_banister =", value, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterNotEqualTo(Integer value) {
            addCriterion("groud_sensor_banister <>", value, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterGreaterThan(Integer value) {
            addCriterion("groud_sensor_banister >", value, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterGreaterThanOrEqualTo(Integer value) {
            addCriterion("groud_sensor_banister >=", value, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterLessThan(Integer value) {
            addCriterion("groud_sensor_banister <", value, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterLessThanOrEqualTo(Integer value) {
            addCriterion("groud_sensor_banister <=", value, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterIn(List<Integer> values) {
            addCriterion("groud_sensor_banister in", values, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterNotIn(List<Integer> values) {
            addCriterion("groud_sensor_banister not in", values, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterBetween(Integer value1, Integer value2) {
            addCriterion("groud_sensor_banister between", value1, value2, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andGroudSensorBanisterNotBetween(Integer value1, Integer value2) {
            addCriterion("groud_sensor_banister not between", value1, value2, "groudSensorBanister");
            return (Criteria) this;
        }

        public Criteria andCameraStausIsNull() {
            addCriterion("camera_staus is null");
            return (Criteria) this;
        }

        public Criteria andCameraStausIsNotNull() {
            addCriterion("camera_staus is not null");
            return (Criteria) this;
        }

        public Criteria andCameraStausEqualTo(Integer value) {
            addCriterion("camera_staus =", value, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausNotEqualTo(Integer value) {
            addCriterion("camera_staus <>", value, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausGreaterThan(Integer value) {
            addCriterion("camera_staus >", value, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausGreaterThanOrEqualTo(Integer value) {
            addCriterion("camera_staus >=", value, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausLessThan(Integer value) {
            addCriterion("camera_staus <", value, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausLessThanOrEqualTo(Integer value) {
            addCriterion("camera_staus <=", value, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausIn(List<Integer> values) {
            addCriterion("camera_staus in", values, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausNotIn(List<Integer> values) {
            addCriterion("camera_staus not in", values, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausBetween(Integer value1, Integer value2) {
            addCriterion("camera_staus between", value1, value2, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andCameraStausNotBetween(Integer value1, Integer value2) {
            addCriterion("camera_staus not between", value1, value2, "cameraStaus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusIsNull() {
            addCriterion("banister_status is null");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusIsNotNull() {
            addCriterion("banister_status is not null");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusEqualTo(Integer value) {
            addCriterion("banister_status =", value, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusNotEqualTo(Integer value) {
            addCriterion("banister_status <>", value, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusGreaterThan(Integer value) {
            addCriterion("banister_status >", value, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("banister_status >=", value, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusLessThan(Integer value) {
            addCriterion("banister_status <", value, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusLessThanOrEqualTo(Integer value) {
            addCriterion("banister_status <=", value, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusIn(List<Integer> values) {
            addCriterion("banister_status in", values, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusNotIn(List<Integer> values) {
            addCriterion("banister_status not in", values, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusBetween(Integer value1, Integer value2) {
            addCriterion("banister_status between", value1, value2, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andBanisterStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("banister_status not between", value1, value2, "banisterStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusIsNull() {
            addCriterion("alarm_status is null");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusIsNotNull() {
            addCriterion("alarm_status is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusEqualTo(Integer value) {
            addCriterion("alarm_status =", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusNotEqualTo(Integer value) {
            addCriterion("alarm_status <>", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusGreaterThan(Integer value) {
            addCriterion("alarm_status >", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_status >=", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusLessThan(Integer value) {
            addCriterion("alarm_status <", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_status <=", value, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusIn(List<Integer> values) {
            addCriterion("alarm_status in", values, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusNotIn(List<Integer> values) {
            addCriterion("alarm_status not in", values, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusBetween(Integer value1, Integer value2) {
            addCriterion("alarm_status between", value1, value2, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_status not between", value1, value2, "alarmStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusIsNull() {
            addCriterion("lane_status is null");
            return (Criteria) this;
        }

        public Criteria andLaneStatusIsNotNull() {
            addCriterion("lane_status is not null");
            return (Criteria) this;
        }

        public Criteria andLaneStatusEqualTo(Integer value) {
            addCriterion("lane_status =", value, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusNotEqualTo(Integer value) {
            addCriterion("lane_status <>", value, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusGreaterThan(Integer value) {
            addCriterion("lane_status >", value, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("lane_status >=", value, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusLessThan(Integer value) {
            addCriterion("lane_status <", value, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusLessThanOrEqualTo(Integer value) {
            addCriterion("lane_status <=", value, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusIn(List<Integer> values) {
            addCriterion("lane_status in", values, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusNotIn(List<Integer> values) {
            addCriterion("lane_status not in", values, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusBetween(Integer value1, Integer value2) {
            addCriterion("lane_status between", value1, value2, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andLaneStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("lane_status not between", value1, value2, "laneStatus");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelIsNull() {
            addCriterion("alarm_level is null");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelIsNotNull() {
            addCriterion("alarm_level is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelEqualTo(Integer value) {
            addCriterion("alarm_level =", value, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelNotEqualTo(Integer value) {
            addCriterion("alarm_level <>", value, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelGreaterThan(Integer value) {
            addCriterion("alarm_level >", value, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_level >=", value, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelLessThan(Integer value) {
            addCriterion("alarm_level <", value, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_level <=", value, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelIn(List<Integer> values) {
            addCriterion("alarm_level in", values, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelNotIn(List<Integer> values) {
            addCriterion("alarm_level not in", values, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelBetween(Integer value1, Integer value2) {
            addCriterion("alarm_level between", value1, value2, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_level not between", value1, value2, "alarmLevel");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeIsNull() {
            addCriterion("alarm_time is null");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeIsNotNull() {
            addCriterion("alarm_time is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeEqualTo(String value) {
            addCriterion("alarm_time =", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeNotEqualTo(String value) {
            addCriterion("alarm_time <>", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeGreaterThan(String value) {
            addCriterion("alarm_time >", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeGreaterThanOrEqualTo(String value) {
            addCriterion("alarm_time >=", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeLessThan(String value) {
            addCriterion("alarm_time <", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeLessThanOrEqualTo(String value) {
            addCriterion("alarm_time <=", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeLike(String value) {
            addCriterion("alarm_time like", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeNotLike(String value) {
            addCriterion("alarm_time not like", value, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeIn(List<String> values) {
            addCriterion("alarm_time in", values, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeNotIn(List<String> values) {
            addCriterion("alarm_time not in", values, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeBetween(String value1, String value2) {
            addCriterion("alarm_time between", value1, value2, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andAlarmTimeNotBetween(String value1, String value2) {
            addCriterion("alarm_time not between", value1, value2, "alarmTime");
            return (Criteria) this;
        }

        public Criteria andDealStatusIsNull() {
            addCriterion("deal_status is null");
            return (Criteria) this;
        }

        public Criteria andDealStatusIsNotNull() {
            addCriterion("deal_status is not null");
            return (Criteria) this;
        }

        public Criteria andDealStatusEqualTo(Integer value) {
            addCriterion("deal_status =", value, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusNotEqualTo(Integer value) {
            addCriterion("deal_status <>", value, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusGreaterThan(Integer value) {
            addCriterion("deal_status >", value, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_status >=", value, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusLessThan(Integer value) {
            addCriterion("deal_status <", value, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusLessThanOrEqualTo(Integer value) {
            addCriterion("deal_status <=", value, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusIn(List<Integer> values) {
            addCriterion("deal_status in", values, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusNotIn(List<Integer> values) {
            addCriterion("deal_status not in", values, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusBetween(Integer value1, Integer value2) {
            addCriterion("deal_status between", value1, value2, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andDealStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_status not between", value1, value2, "dealStatus");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_alarm_message
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_alarm_message
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}