package com.ump.entity;

public class TDealLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deal_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deal_log.deal_type
     *
     * @mbg.generated
     */
    private Integer dealType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deal_log.deal_content
     *
     * @mbg.generated
     */
    private String dealContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deal_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deal_log.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deal_log.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deal_log.id
     *
     * @return the value of t_deal_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deal_log.id
     *
     * @param id the value for t_deal_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deal_log.deal_type
     *
     * @return the value of t_deal_log.deal_type
     *
     * @mbg.generated
     */
    public Integer getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deal_log.deal_type
     *
     * @param dealType the value for t_deal_log.deal_type
     *
     * @mbg.generated
     */
    public void setDealType(Integer dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deal_log.deal_content
     *
     * @return the value of t_deal_log.deal_content
     *
     * @mbg.generated
     */
    public String getDealContent() {
        return dealContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deal_log.deal_content
     *
     * @param dealContent the value for t_deal_log.deal_content
     *
     * @mbg.generated
     */
    public void setDealContent(String dealContent) {
        this.dealContent = dealContent == null ? null : dealContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deal_log.user_id
     *
     * @return the value of t_deal_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deal_log.user_id
     *
     * @param userId the value for t_deal_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deal_log.user_name
     *
     * @return the value of t_deal_log.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deal_log.user_name
     *
     * @param userName the value for t_deal_log.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deal_log.create_time
     *
     * @return the value of t_deal_log.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deal_log.create_time
     *
     * @param createTime the value for t_deal_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}