package com.ump.entity;

public class TParkPortStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.park_name
     *
     * @mbg.generated
     */
    private String parkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.port_id
     *
     * @mbg.generated
     */
    private String portId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.inoutType
     *
     * @mbg.generated
     */
    private Integer inouttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.ipcSn
     *
     * @mbg.generated
     */
    private String ipcsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.auxIpc1Sn
     *
     * @mbg.generated
     */
    private String auxipc1sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.auxIpc2Sn
     *
     * @mbg.generated
     */
    private String auxipc2sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.softwareVer
     *
     * @mbg.generated
     */
    private String softwarever;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.IPCofflinelist
     *
     * @mbg.generated
     */
    private String ipcofflinelist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.port_name
     *
     * @mbg.generated
     */
    private String portName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.computer_name
     *
     * @mbg.generated
     */
    private String computerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.id_address
     *
     * @mbg.generated
     */
    private String idAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.online_status
     *
     * @mbg.generated
     */
    private Integer onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.carIn_flow
     *
     * @mbg.generated
     */
    private String carinFlow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.groud_sensor_camera
     *
     * @mbg.generated
     */
    private Integer groudSensorCamera;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.groud_sensor_banister
     *
     * @mbg.generated
     */
    private Integer groudSensorBanister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.camera_staus
     *
     * @mbg.generated
     */
    private Integer cameraStaus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.banister_status
     *
     * @mbg.generated
     */
    private Integer banisterStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.alarm_status
     *
     * @mbg.generated
     */
    private Integer alarmStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.camera_carplate
     *
     * @mbg.generated
     */
    private String cameraCarplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.camera_url
     *
     * @mbg.generated
     */
    private String cameraUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.lane_status
     *
     * @mbg.generated
     */
    private Integer laneStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.ipc_offline
     *
     * @mbg.generated
     */
    private Integer ipcOffline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.deal_user_id
     *
     * @mbg.generated
     */
    private Integer dealUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.deal_user_name
     *
     * @mbg.generated
     */
    private String dealUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.deal_status
     *
     * @mbg.generated
     */
    private Integer dealStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port_status.deal_date
     *
     * @mbg.generated
     */
    private String dealDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.id
     *
     * @return the value of t_park_port_status.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.id
     *
     * @param id the value for t_park_port_status.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.park_id
     *
     * @return the value of t_park_port_status.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.park_id
     *
     * @param parkId the value for t_park_port_status.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.park_name
     *
     * @return the value of t_park_port_status.park_name
     *
     * @mbg.generated
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.park_name
     *
     * @param parkName the value for t_park_port_status.park_name
     *
     * @mbg.generated
     */
    public void setParkName(String parkName) {
        this.parkName = parkName == null ? null : parkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.port_id
     *
     * @return the value of t_park_port_status.port_id
     *
     * @mbg.generated
     */
    public String getPortId() {
        return portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.port_id
     *
     * @param portId the value for t_park_port_status.port_id
     *
     * @mbg.generated
     */
    public void setPortId(String portId) {
        this.portId = portId == null ? null : portId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.inoutType
     *
     * @return the value of t_park_port_status.inoutType
     *
     * @mbg.generated
     */
    public Integer getInouttype() {
        return inouttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.inoutType
     *
     * @param inouttype the value for t_park_port_status.inoutType
     *
     * @mbg.generated
     */
    public void setInouttype(Integer inouttype) {
        this.inouttype = inouttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.ipcSn
     *
     * @return the value of t_park_port_status.ipcSn
     *
     * @mbg.generated
     */
    public String getIpcsn() {
        return ipcsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.ipcSn
     *
     * @param ipcsn the value for t_park_port_status.ipcSn
     *
     * @mbg.generated
     */
    public void setIpcsn(String ipcsn) {
        this.ipcsn = ipcsn == null ? null : ipcsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.auxIpc1Sn
     *
     * @return the value of t_park_port_status.auxIpc1Sn
     *
     * @mbg.generated
     */
    public String getAuxipc1sn() {
        return auxipc1sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.auxIpc1Sn
     *
     * @param auxipc1sn the value for t_park_port_status.auxIpc1Sn
     *
     * @mbg.generated
     */
    public void setAuxipc1sn(String auxipc1sn) {
        this.auxipc1sn = auxipc1sn == null ? null : auxipc1sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.auxIpc2Sn
     *
     * @return the value of t_park_port_status.auxIpc2Sn
     *
     * @mbg.generated
     */
    public String getAuxipc2sn() {
        return auxipc2sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.auxIpc2Sn
     *
     * @param auxipc2sn the value for t_park_port_status.auxIpc2Sn
     *
     * @mbg.generated
     */
    public void setAuxipc2sn(String auxipc2sn) {
        this.auxipc2sn = auxipc2sn == null ? null : auxipc2sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.softwareVer
     *
     * @return the value of t_park_port_status.softwareVer
     *
     * @mbg.generated
     */
    public String getSoftwarever() {
        return softwarever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.softwareVer
     *
     * @param softwarever the value for t_park_port_status.softwareVer
     *
     * @mbg.generated
     */
    public void setSoftwarever(String softwarever) {
        this.softwarever = softwarever == null ? null : softwarever.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.IPCofflinelist
     *
     * @return the value of t_park_port_status.IPCofflinelist
     *
     * @mbg.generated
     */
    public String getIpcofflinelist() {
        return ipcofflinelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.IPCofflinelist
     *
     * @param ipcofflinelist the value for t_park_port_status.IPCofflinelist
     *
     * @mbg.generated
     */
    public void setIpcofflinelist(String ipcofflinelist) {
        this.ipcofflinelist = ipcofflinelist == null ? null : ipcofflinelist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.port_name
     *
     * @return the value of t_park_port_status.port_name
     *
     * @mbg.generated
     */
    public String getPortName() {
        return portName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.port_name
     *
     * @param portName the value for t_park_port_status.port_name
     *
     * @mbg.generated
     */
    public void setPortName(String portName) {
        this.portName = portName == null ? null : portName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.computer_name
     *
     * @return the value of t_park_port_status.computer_name
     *
     * @mbg.generated
     */
    public String getComputerName() {
        return computerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.computer_name
     *
     * @param computerName the value for t_park_port_status.computer_name
     *
     * @mbg.generated
     */
    public void setComputerName(String computerName) {
        this.computerName = computerName == null ? null : computerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.id_address
     *
     * @return the value of t_park_port_status.id_address
     *
     * @mbg.generated
     */
    public String getIdAddress() {
        return idAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.id_address
     *
     * @param idAddress the value for t_park_port_status.id_address
     *
     * @mbg.generated
     */
    public void setIdAddress(String idAddress) {
        this.idAddress = idAddress == null ? null : idAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.online_status
     *
     * @return the value of t_park_port_status.online_status
     *
     * @mbg.generated
     */
    public Integer getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.online_status
     *
     * @param onlineStatus the value for t_park_port_status.online_status
     *
     * @mbg.generated
     */
    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.carIn_flow
     *
     * @return the value of t_park_port_status.carIn_flow
     *
     * @mbg.generated
     */
    public String getCarinFlow() {
        return carinFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.carIn_flow
     *
     * @param carinFlow the value for t_park_port_status.carIn_flow
     *
     * @mbg.generated
     */
    public void setCarinFlow(String carinFlow) {
        this.carinFlow = carinFlow == null ? null : carinFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.groud_sensor_camera
     *
     * @return the value of t_park_port_status.groud_sensor_camera
     *
     * @mbg.generated
     */
    public Integer getGroudSensorCamera() {
        return groudSensorCamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.groud_sensor_camera
     *
     * @param groudSensorCamera the value for t_park_port_status.groud_sensor_camera
     *
     * @mbg.generated
     */
    public void setGroudSensorCamera(Integer groudSensorCamera) {
        this.groudSensorCamera = groudSensorCamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.groud_sensor_banister
     *
     * @return the value of t_park_port_status.groud_sensor_banister
     *
     * @mbg.generated
     */
    public Integer getGroudSensorBanister() {
        return groudSensorBanister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.groud_sensor_banister
     *
     * @param groudSensorBanister the value for t_park_port_status.groud_sensor_banister
     *
     * @mbg.generated
     */
    public void setGroudSensorBanister(Integer groudSensorBanister) {
        this.groudSensorBanister = groudSensorBanister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.camera_staus
     *
     * @return the value of t_park_port_status.camera_staus
     *
     * @mbg.generated
     */
    public Integer getCameraStaus() {
        return cameraStaus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.camera_staus
     *
     * @param cameraStaus the value for t_park_port_status.camera_staus
     *
     * @mbg.generated
     */
    public void setCameraStaus(Integer cameraStaus) {
        this.cameraStaus = cameraStaus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.banister_status
     *
     * @return the value of t_park_port_status.banister_status
     *
     * @mbg.generated
     */
    public Integer getBanisterStatus() {
        return banisterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.banister_status
     *
     * @param banisterStatus the value for t_park_port_status.banister_status
     *
     * @mbg.generated
     */
    public void setBanisterStatus(Integer banisterStatus) {
        this.banisterStatus = banisterStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.alarm_status
     *
     * @return the value of t_park_port_status.alarm_status
     *
     * @mbg.generated
     */
    public Integer getAlarmStatus() {
        return alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.alarm_status
     *
     * @param alarmStatus the value for t_park_port_status.alarm_status
     *
     * @mbg.generated
     */
    public void setAlarmStatus(Integer alarmStatus) {
        this.alarmStatus = alarmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.camera_carplate
     *
     * @return the value of t_park_port_status.camera_carplate
     *
     * @mbg.generated
     */
    public String getCameraCarplate() {
        return cameraCarplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.camera_carplate
     *
     * @param cameraCarplate the value for t_park_port_status.camera_carplate
     *
     * @mbg.generated
     */
    public void setCameraCarplate(String cameraCarplate) {
        this.cameraCarplate = cameraCarplate == null ? null : cameraCarplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.camera_url
     *
     * @return the value of t_park_port_status.camera_url
     *
     * @mbg.generated
     */
    public String getCameraUrl() {
        return cameraUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.camera_url
     *
     * @param cameraUrl the value for t_park_port_status.camera_url
     *
     * @mbg.generated
     */
    public void setCameraUrl(String cameraUrl) {
        this.cameraUrl = cameraUrl == null ? null : cameraUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.lane_status
     *
     * @return the value of t_park_port_status.lane_status
     *
     * @mbg.generated
     */
    public Integer getLaneStatus() {
        return laneStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.lane_status
     *
     * @param laneStatus the value for t_park_port_status.lane_status
     *
     * @mbg.generated
     */
    public void setLaneStatus(Integer laneStatus) {
        this.laneStatus = laneStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.ipc_offline
     *
     * @return the value of t_park_port_status.ipc_offline
     *
     * @mbg.generated
     */
    public Integer getIpcOffline() {
        return ipcOffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.ipc_offline
     *
     * @param ipcOffline the value for t_park_port_status.ipc_offline
     *
     * @mbg.generated
     */
    public void setIpcOffline(Integer ipcOffline) {
        this.ipcOffline = ipcOffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.deal_user_id
     *
     * @return the value of t_park_port_status.deal_user_id
     *
     * @mbg.generated
     */
    public Integer getDealUserId() {
        return dealUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.deal_user_id
     *
     * @param dealUserId the value for t_park_port_status.deal_user_id
     *
     * @mbg.generated
     */
    public void setDealUserId(Integer dealUserId) {
        this.dealUserId = dealUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.deal_user_name
     *
     * @return the value of t_park_port_status.deal_user_name
     *
     * @mbg.generated
     */
    public String getDealUserName() {
        return dealUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.deal_user_name
     *
     * @param dealUserName the value for t_park_port_status.deal_user_name
     *
     * @mbg.generated
     */
    public void setDealUserName(String dealUserName) {
        this.dealUserName = dealUserName == null ? null : dealUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.deal_status
     *
     * @return the value of t_park_port_status.deal_status
     *
     * @mbg.generated
     */
    public Integer getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.deal_status
     *
     * @param dealStatus the value for t_park_port_status.deal_status
     *
     * @mbg.generated
     */
    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port_status.deal_date
     *
     * @return the value of t_park_port_status.deal_date
     *
     * @mbg.generated
     */
    public String getDealDate() {
        return dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port_status.deal_date
     *
     * @param dealDate the value for t_park_port_status.deal_date
     *
     * @mbg.generated
     */
    public void setDealDate(String dealDate) {
        this.dealDate = dealDate == null ? null : dealDate.trim();
    }
}