package com.ump.dao.sqlProvider;

import com.ump.entity.TParkPortStatus;
import com.ump.entity.TParkPortStatusCriteria;
import com.ump.entity.TParkPortStatusCriteria.Criteria;
import com.ump.entity.TParkPortStatusCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TParkPortStatusSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    public String countByExample(TParkPortStatusCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_park_port_status");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    public String deleteByExample(TParkPortStatusCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_park_port_status");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    public String insertSelective(TParkPortStatus record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_park_port_status");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getParkName() != null) {
            sql.VALUES("park_name", "#{parkName,jdbcType=VARCHAR}");
        }
        
        if (record.getPortId() != null) {
            sql.VALUES("port_id", "#{portId,jdbcType=VARCHAR}");
        }
        
        if (record.getInouttype() != null) {
            sql.VALUES("inoutType", "#{inouttype,jdbcType=INTEGER}");
        }
        
        if (record.getIpcsn() != null) {
            sql.VALUES("ipcSn", "#{ipcsn,jdbcType=VARCHAR}");
        }
        
        if (record.getAuxipc1sn() != null) {
            sql.VALUES("auxIpc1Sn", "#{auxipc1sn,jdbcType=VARCHAR}");
        }
        
        if (record.getAuxipc2sn() != null) {
            sql.VALUES("auxIpc2Sn", "#{auxipc2sn,jdbcType=VARCHAR}");
        }
        
        if (record.getSoftwarever() != null) {
            sql.VALUES("softwareVer", "#{softwarever,jdbcType=VARCHAR}");
        }
        
        if (record.getIpcofflinelist() != null) {
            sql.VALUES("IPCofflinelist", "#{ipcofflinelist,jdbcType=VARCHAR}");
        }
        
        if (record.getPortName() != null) {
            sql.VALUES("port_name", "#{portName,jdbcType=VARCHAR}");
        }
        
        if (record.getComputerName() != null) {
            sql.VALUES("computer_name", "#{computerName,jdbcType=VARCHAR}");
        }
        
        if (record.getIdAddress() != null) {
            sql.VALUES("id_address", "#{idAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getOnlineStatus() != null) {
            sql.VALUES("online_status", "#{onlineStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCarinFlow() != null) {
            sql.VALUES("carIn_flow", "#{carinFlow,jdbcType=VARCHAR}");
        }
        
        if (record.getGroudSensorCamera() != null) {
            sql.VALUES("groud_sensor_camera", "#{groudSensorCamera,jdbcType=INTEGER}");
        }
        
        if (record.getGroudSensorBanister() != null) {
            sql.VALUES("groud_sensor_banister", "#{groudSensorBanister,jdbcType=INTEGER}");
        }
        
        if (record.getCameraStaus() != null) {
            sql.VALUES("camera_staus", "#{cameraStaus,jdbcType=INTEGER}");
        }
        
        if (record.getBanisterStatus() != null) {
            sql.VALUES("banister_status", "#{banisterStatus,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmStatus() != null) {
            sql.VALUES("alarm_status", "#{alarmStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCameraCarplate() != null) {
            sql.VALUES("camera_carplate", "#{cameraCarplate,jdbcType=VARCHAR}");
        }
        
        if (record.getCameraUrl() != null) {
            sql.VALUES("camera_url", "#{cameraUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getLaneStatus() != null) {
            sql.VALUES("lane_status", "#{laneStatus,jdbcType=INTEGER}");
        }
        
        if (record.getIpcOffline() != null) {
            sql.VALUES("ipc_offline", "#{ipcOffline,jdbcType=INTEGER}");
        }
        
        if (record.getDealUserId() != null) {
            sql.VALUES("deal_user_id", "#{dealUserId,jdbcType=INTEGER}");
        }
        
        if (record.getDealUserName() != null) {
            sql.VALUES("deal_user_name", "#{dealUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getDealStatus() != null) {
            sql.VALUES("deal_status", "#{dealStatus,jdbcType=INTEGER}");
        }
        
        if (record.getDealDate() != null) {
            sql.VALUES("deal_date", "#{dealDate,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    public String selectByExample(TParkPortStatusCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("park_id");
        sql.SELECT("park_name");
        sql.SELECT("port_id");
        sql.SELECT("inoutType");
        sql.SELECT("ipcSn");
        sql.SELECT("auxIpc1Sn");
        sql.SELECT("auxIpc2Sn");
        sql.SELECT("softwareVer");
        sql.SELECT("IPCofflinelist");
        sql.SELECT("port_name");
        sql.SELECT("computer_name");
        sql.SELECT("id_address");
        sql.SELECT("online_status");
        sql.SELECT("carIn_flow");
        sql.SELECT("groud_sensor_camera");
        sql.SELECT("groud_sensor_banister");
        sql.SELECT("camera_staus");
        sql.SELECT("banister_status");
        sql.SELECT("alarm_status");
        sql.SELECT("camera_carplate");
        sql.SELECT("camera_url");
        sql.SELECT("lane_status");
        sql.SELECT("ipc_offline");
        sql.SELECT("deal_user_id");
        sql.SELECT("deal_user_name");
        sql.SELECT("deal_status");
        sql.SELECT("deal_date");
        sql.FROM("t_park_port_status");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TParkPortStatus record = (TParkPortStatus) parameter.get("record");
        TParkPortStatusCriteria example = (TParkPortStatusCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_park_port_status");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getParkName() != null) {
            sql.SET("park_name = #{record.parkName,jdbcType=VARCHAR}");
        }
        
        if (record.getPortId() != null) {
            sql.SET("port_id = #{record.portId,jdbcType=VARCHAR}");
        }
        
        if (record.getInouttype() != null) {
            sql.SET("inoutType = #{record.inouttype,jdbcType=INTEGER}");
        }
        
        if (record.getIpcsn() != null) {
            sql.SET("ipcSn = #{record.ipcsn,jdbcType=VARCHAR}");
        }
        
        if (record.getAuxipc1sn() != null) {
            sql.SET("auxIpc1Sn = #{record.auxipc1sn,jdbcType=VARCHAR}");
        }
        
        if (record.getAuxipc2sn() != null) {
            sql.SET("auxIpc2Sn = #{record.auxipc2sn,jdbcType=VARCHAR}");
        }
        
        if (record.getSoftwarever() != null) {
            sql.SET("softwareVer = #{record.softwarever,jdbcType=VARCHAR}");
        }
        
        if (record.getIpcofflinelist() != null) {
            sql.SET("IPCofflinelist = #{record.ipcofflinelist,jdbcType=VARCHAR}");
        }
        
        if (record.getPortName() != null) {
            sql.SET("port_name = #{record.portName,jdbcType=VARCHAR}");
        }
        
        if (record.getComputerName() != null) {
            sql.SET("computer_name = #{record.computerName,jdbcType=VARCHAR}");
        }
        
        if (record.getIdAddress() != null) {
            sql.SET("id_address = #{record.idAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getOnlineStatus() != null) {
            sql.SET("online_status = #{record.onlineStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCarinFlow() != null) {
            sql.SET("carIn_flow = #{record.carinFlow,jdbcType=VARCHAR}");
        }
        
        if (record.getGroudSensorCamera() != null) {
            sql.SET("groud_sensor_camera = #{record.groudSensorCamera,jdbcType=INTEGER}");
        }
        
        if (record.getGroudSensorBanister() != null) {
            sql.SET("groud_sensor_banister = #{record.groudSensorBanister,jdbcType=INTEGER}");
        }
        
        if (record.getCameraStaus() != null) {
            sql.SET("camera_staus = #{record.cameraStaus,jdbcType=INTEGER}");
        }
        
        if (record.getBanisterStatus() != null) {
            sql.SET("banister_status = #{record.banisterStatus,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmStatus() != null) {
            sql.SET("alarm_status = #{record.alarmStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCameraCarplate() != null) {
            sql.SET("camera_carplate = #{record.cameraCarplate,jdbcType=VARCHAR}");
        }
        
        if (record.getCameraUrl() != null) {
            sql.SET("camera_url = #{record.cameraUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getLaneStatus() != null) {
            sql.SET("lane_status = #{record.laneStatus,jdbcType=INTEGER}");
        }
        
        if (record.getIpcOffline() != null) {
            sql.SET("ipc_offline = #{record.ipcOffline,jdbcType=INTEGER}");
        }
        
        if (record.getDealUserId() != null) {
            sql.SET("deal_user_id = #{record.dealUserId,jdbcType=INTEGER}");
        }
        
        if (record.getDealUserName() != null) {
            sql.SET("deal_user_name = #{record.dealUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getDealStatus() != null) {
            sql.SET("deal_status = #{record.dealStatus,jdbcType=INTEGER}");
        }
        
        if (record.getDealDate() != null) {
            sql.SET("deal_date = #{record.dealDate,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_park_port_status");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("park_name = #{record.parkName,jdbcType=VARCHAR}");
        sql.SET("port_id = #{record.portId,jdbcType=VARCHAR}");
        sql.SET("inoutType = #{record.inouttype,jdbcType=INTEGER}");
        sql.SET("ipcSn = #{record.ipcsn,jdbcType=VARCHAR}");
        sql.SET("auxIpc1Sn = #{record.auxipc1sn,jdbcType=VARCHAR}");
        sql.SET("auxIpc2Sn = #{record.auxipc2sn,jdbcType=VARCHAR}");
        sql.SET("softwareVer = #{record.softwarever,jdbcType=VARCHAR}");
        sql.SET("IPCofflinelist = #{record.ipcofflinelist,jdbcType=VARCHAR}");
        sql.SET("port_name = #{record.portName,jdbcType=VARCHAR}");
        sql.SET("computer_name = #{record.computerName,jdbcType=VARCHAR}");
        sql.SET("id_address = #{record.idAddress,jdbcType=VARCHAR}");
        sql.SET("online_status = #{record.onlineStatus,jdbcType=INTEGER}");
        sql.SET("carIn_flow = #{record.carinFlow,jdbcType=VARCHAR}");
        sql.SET("groud_sensor_camera = #{record.groudSensorCamera,jdbcType=INTEGER}");
        sql.SET("groud_sensor_banister = #{record.groudSensorBanister,jdbcType=INTEGER}");
        sql.SET("camera_staus = #{record.cameraStaus,jdbcType=INTEGER}");
        sql.SET("banister_status = #{record.banisterStatus,jdbcType=INTEGER}");
        sql.SET("alarm_status = #{record.alarmStatus,jdbcType=INTEGER}");
        sql.SET("camera_carplate = #{record.cameraCarplate,jdbcType=VARCHAR}");
        sql.SET("camera_url = #{record.cameraUrl,jdbcType=VARCHAR}");
        sql.SET("lane_status = #{record.laneStatus,jdbcType=INTEGER}");
        sql.SET("ipc_offline = #{record.ipcOffline,jdbcType=INTEGER}");
        sql.SET("deal_user_id = #{record.dealUserId,jdbcType=INTEGER}");
        sql.SET("deal_user_name = #{record.dealUserName,jdbcType=VARCHAR}");
        sql.SET("deal_status = #{record.dealStatus,jdbcType=INTEGER}");
        sql.SET("deal_date = #{record.dealDate,jdbcType=VARCHAR}");
        
        TParkPortStatusCriteria example = (TParkPortStatusCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TParkPortStatus record) {
        SQL sql = new SQL();
        sql.UPDATE("t_park_port_status");
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getParkName() != null) {
            sql.SET("park_name = #{parkName,jdbcType=VARCHAR}");
        }
        
        if (record.getPortId() != null) {
            sql.SET("port_id = #{portId,jdbcType=VARCHAR}");
        }
        
        if (record.getInouttype() != null) {
            sql.SET("inoutType = #{inouttype,jdbcType=INTEGER}");
        }
        
        if (record.getIpcsn() != null) {
            sql.SET("ipcSn = #{ipcsn,jdbcType=VARCHAR}");
        }
        
        if (record.getAuxipc1sn() != null) {
            sql.SET("auxIpc1Sn = #{auxipc1sn,jdbcType=VARCHAR}");
        }
        
        if (record.getAuxipc2sn() != null) {
            sql.SET("auxIpc2Sn = #{auxipc2sn,jdbcType=VARCHAR}");
        }
        
        if (record.getSoftwarever() != null) {
            sql.SET("softwareVer = #{softwarever,jdbcType=VARCHAR}");
        }
        
        if (record.getIpcofflinelist() != null) {
            sql.SET("IPCofflinelist = #{ipcofflinelist,jdbcType=VARCHAR}");
        }
        
        if (record.getPortName() != null) {
            sql.SET("port_name = #{portName,jdbcType=VARCHAR}");
        }
        
        if (record.getComputerName() != null) {
            sql.SET("computer_name = #{computerName,jdbcType=VARCHAR}");
        }
        
        if (record.getIdAddress() != null) {
            sql.SET("id_address = #{idAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getOnlineStatus() != null) {
            sql.SET("online_status = #{onlineStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCarinFlow() != null) {
            sql.SET("carIn_flow = #{carinFlow,jdbcType=VARCHAR}");
        }
        
        if (record.getGroudSensorCamera() != null) {
            sql.SET("groud_sensor_camera = #{groudSensorCamera,jdbcType=INTEGER}");
        }
        
        if (record.getGroudSensorBanister() != null) {
            sql.SET("groud_sensor_banister = #{groudSensorBanister,jdbcType=INTEGER}");
        }
        
        if (record.getCameraStaus() != null) {
            sql.SET("camera_staus = #{cameraStaus,jdbcType=INTEGER}");
        }
        
        if (record.getBanisterStatus() != null) {
            sql.SET("banister_status = #{banisterStatus,jdbcType=INTEGER}");
        }
        
        if (record.getAlarmStatus() != null) {
            sql.SET("alarm_status = #{alarmStatus,jdbcType=INTEGER}");
        }
        
        if (record.getCameraCarplate() != null) {
            sql.SET("camera_carplate = #{cameraCarplate,jdbcType=VARCHAR}");
        }
        
        if (record.getCameraUrl() != null) {
            sql.SET("camera_url = #{cameraUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getLaneStatus() != null) {
            sql.SET("lane_status = #{laneStatus,jdbcType=INTEGER}");
        }
        
        if (record.getIpcOffline() != null) {
            sql.SET("ipc_offline = #{ipcOffline,jdbcType=INTEGER}");
        }
        
        if (record.getDealUserId() != null) {
            sql.SET("deal_user_id = #{dealUserId,jdbcType=INTEGER}");
        }
        
        if (record.getDealUserName() != null) {
            sql.SET("deal_user_name = #{dealUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getDealStatus() != null) {
            sql.SET("deal_status = #{dealStatus,jdbcType=INTEGER}");
        }
        
        if (record.getDealDate() != null) {
            sql.SET("deal_date = #{dealDate,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_park_port_status
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TParkPortStatusCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}