package com.ump.dao;

import com.ump.dao.sqlProvider.TDealLogSqlProvider;
import com.ump.entity.TDealLog;
import com.ump.entity.TDealLogCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TDealLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @SelectProvider(type= TDealLogSqlProvider.class, method="countByExample")
    long countByExample(TDealLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TDealLogSqlProvider.class, method="deleteByExample")
    int deleteByExample(TDealLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_deal_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_deal_log (id, deal_type, ",
        "deal_content, user_id, ",
        "user_name, create_time)",
        "values (#{id,jdbcType=INTEGER}, #{dealType,jdbcType=INTEGER}, ",
        "#{dealContent,jdbcType=VARCHAR}, #{userId,jdbcType=INTEGER}, ",
        "#{userName,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR})"
    })
    int insert(TDealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @InsertProvider(type=TDealLogSqlProvider.class, method="insertSelective")
    int insertSelective(TDealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @SelectProvider(type=TDealLogSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="deal_type", property="dealType", jdbcType=JdbcType.INTEGER),
        @Result(column="deal_content", property="dealContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR)
    })
    List<TDealLog> selectByExample(TDealLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, deal_type, deal_content, user_id, user_name, create_time",
        "from t_deal_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="deal_type", property="dealType", jdbcType=JdbcType.INTEGER),
        @Result(column="deal_content", property="dealContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR)
    })
    TDealLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDealLogSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TDealLog record, @Param("example") TDealLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDealLogSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TDealLog record, @Param("example") TDealLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDealLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TDealLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deal_log
     *
     * @mbg.generated
     */
    @Update({
        "update t_deal_log",
        "set deal_type = #{dealType,jdbcType=INTEGER},",
          "deal_content = #{dealContent,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TDealLog record);
}